NineNineCats/config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests, only: [:create, :new, :edit, :update]
end

NineNineCats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

require 'Date'

class Cat <ActiveRecord::Base

  validates :birth_date, :color, :name, :sex, presence: true
  validates :sex, inclusion: { in: %w(M F)}
  validates :color, inclusion: { in: %w(Black White Orange Yellow)}

  def age
    DateTime.now.year - birth_date.year
  end

  has_many :cat_rental_requests,
    :dependent => :destroy
end

NineNineCats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime
#  updated_at :datetime
#

class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: %w(PENDING DENIED APPROVED)}
  validate :does_not_overlap_approved_request

  belongs_to :cat

  def overlapping_requests
    CatRentalRequest
      .where("(:id IS NULL) OR (id != :id)", id: self.id)
      .where(cat_id: cat_id)
      .where(<<-SQL, start_date: start_date, end_date: end_date)
       NOT( (start_date > :end_date) OR (end_date < :start_date) )
    SQL
  end

  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end

  def denied?
    !overlapping_approved_requests.empty?
  end

  def does_not_overlap_approved_request
    return if self.denied?

    unless overlapping_approved_requests.empty?
      errors[:base] <<
        "Request conflicts with existing approved request"
    end
  end
end

NineNineCats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

NineNineCats/app/controllers/cat_rental_requests_controller.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime
#  updated_at :datetime
#

class CatRentalRequestsController < ApplicationController
  def new
    @catrentals = Cat.all
    render :new
  end

  def create
    @catrentals = CatRentalRequest.new(cat_rental_params)
    if @catrentals.save
      redirect_to cats_url
    else
      fail
      render text: @catrentals.errors.full_messages
    end
  end

  private
  def cat_rental_params
    params.require(:cat_rental_requests).permit(:cat_id, :start_date, :end_date)
  end

end

NineNineCats/app/controllers/cats_controller.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class CatsController < ApplicationController
  def index
    @cat = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    @catrentals = CatRentalRequest.where(cat_id: params[:id])
    if @cat
      render :show
    else
      render json: "cat doesn't exist", status: :not_found
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cats_url
    else
      fail
      render text: @cat.errors.full_messages
    end
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.update(params[:id], cat_params)
    redirect_to cat_url
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :sex, :birth_date, :color, :description)
  end

end

NineNineCats/app/helpers/application_helper.rb
module ApplicationHelper
end

NineNineCats/app/helpers/cat_rental_requests_helper.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime
#  updated_at :datetime
#

module CatRentalRequestsHelper
end

NineNineCats/app/helpers/cats_helper.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

module CatsHelper
end

NineNineCats/app/views/cat_rental_requests/new.html.erb
<form action="<%=cat_rental_requests_url%>" method="post">
  <label for="cat_rental_requests[cat_id]">Requested Cat</label>
  <select name="cat_rental_requests[cat_id]">
    <% @catrentals.each  do |requested_cat|%>
      <%="<option value=\"#{requested_cat.id}\">#{requested_cat.name}</option>".html_safe %>
    <% end %>
  </select>
  <br>
  <label for="cat_rental_requests[start_date]">Start Date</label>
  <input type="date" name = "cat_rental_requests[start_date]">
  <br>
  <label for="cat_rental_requests[end_date]">End Date</label>
  <input type="date" name = "cat_rental_requests[end_date]">
  <br>
  <input type="submit" value="Rent Cat">

NineNineCats/app/views/cats/_form.html.erb
<form action=<%=action == :edit ? "cat_url" : "cats_url"%> method="post">
<%="<input type=\"hidden\" name =\"_method\" value=\"patch\">".html_safe if action == :edit %>
  <label for="cat[name]">Name </label>
  <input type="text" name="cat[name]" value="<%=cat.name%>">
  <br>

  <input type="radio" name="cat[sex]" id="cat_sex_female" value = "F" <%="checked='checked'" if cat.sex == 'F' %>>
  <label for="cat_sex_female">Female</label>
  <input type="radio" name="cat[sex]" id="cat_sex_male" value = "M" <%="checked='checked'" if cat.sex == 'M' %>>
  <label for="cat_sex_male">Male</label>

  <br>
  <label for="cat[color]">Color</label>
  <select name="cat[color]">
    <option value="Black" <%="selected" if cat.color == 'Black'%>>Black</option>
    <option value="White" <%="selected" if cat.color == 'White'%>>White</option>
    <option value="Orange" <%="selected" if cat.color == 'Orange'%>>Orange</option>
    <option value="Yellow" <%="selected" if cat.color == 'Yellow'%>>Yellow</option>
  </select>
  <br>
  <label for="cat[birth_date]">Birth Date</label>
  <input type="date" name = "cat[birth_date]" value=<%=cat.birth_date%>>
  <br>
  <label for="cat[description]">Description</label>
  <textarea name="cat[description]" id="cat_description"><%= cat.description %></textarea>
  <br>
  <input type="submit" value="<%=action == :edit ? "Edit Cat" : "New Cat"%>">
</form>

NineNineCats/app/views/cats/edit.html.erb
<%= render "form", cat: @cat, action: :edit %>

NineNineCats/app/views/cats/index.html.erb
<% @cat.each do |cat| %>
  <%= link_to cat.name, cat_url(cat) %>
  <br>
<% end %>

NineNineCats/app/views/cats/new.html.erb
<%= render "form", cat: @cat, action: :new %>

NineNineCats/app/views/cats/show.html.erb
<table style="width: 50%">
  <tr>
    <th><%= @cat.name %></th>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.age %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.description %></td>
  </tr>
</table>
<br>

<table style="width: 50%">
  <% @cat.cat_rental_requests.each do |rental| %>
    <%= "Start Date: " + rental.start_date.to_s + " End Date: " + rental.end_date.to_s %>
    <br>
  <% end %>
<table>

NineNineCats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NineNineCats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>


<!-- * CatRentalRequest#denied?
* @catrentals should be @cat.cat_rental_requests
* Cat::COLORS -->